DROP DATABASE IF EXISTS guessTheNumberDB;
CREATE DATABASE guessTheNumberDB;

USE guessTheNumberDB;

CREATE TABLE game(
gameID INT PRIMARY KEY AUTO_INCREMENT,
`answer` VARCHAR(50) NOT NULL,
`status` VARCHAR(50) NOT NULL DEFAULT "in progress"
);

CREATE TABLE round(
roundID INT PRIMARY KEY AUTO_INCREMENT,
`guess` VARCHAR(50) NOT NULL,
`time` DATETIME NOT NULL,
gameID INT NOT NULL,
FOREIGN KEY (gameID) REFERENCES game(gameID)
);
